//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace ProjectNhom4 {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsPhieuMuon")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsPhieuMuon : global::System.Data.DataSet {
        
        private dtPhieuMuonDataTable tabledtPhieuMuon;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public dsPhieuMuon() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected dsPhieuMuon(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["dtPhieuMuon"] != null)) {
                    base.Tables.Add(new dtPhieuMuonDataTable(ds.Tables["dtPhieuMuon"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public dtPhieuMuonDataTable dtPhieuMuon {
            get {
                return this.tabledtPhieuMuon;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            dsPhieuMuon cln = ((dsPhieuMuon)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["dtPhieuMuon"] != null)) {
                    base.Tables.Add(new dtPhieuMuonDataTable(ds.Tables["dtPhieuMuon"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tabledtPhieuMuon = ((dtPhieuMuonDataTable)(base.Tables["dtPhieuMuon"]));
            if ((initTable == true)) {
                if ((this.tabledtPhieuMuon != null)) {
                    this.tabledtPhieuMuon.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private void InitClass() {
            this.DataSetName = "dsPhieuMuon";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsPhieuMuon.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabledtPhieuMuon = new dtPhieuMuonDataTable();
            base.Tables.Add(this.tabledtPhieuMuon);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private bool ShouldSerializedtPhieuMuon() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsPhieuMuon ds = new dsPhieuMuon();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public delegate void dtPhieuMuonRowChangeEventHandler(object sender, dtPhieuMuonRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class dtPhieuMuonDataTable : global::System.Data.TypedTableBase<dtPhieuMuonRow> {
            
            private global::System.Data.DataColumn columnMa_Phieu_Muon;
            
            private global::System.Data.DataColumn columnMa_The;
            
            private global::System.Data.DataColumn columnMa_Thu_Thu;
            
            private global::System.Data.DataColumn columnMa_Kieu_Muon;
            
            private global::System.Data.DataColumn columnNgay_Muon;
            
            private global::System.Data.DataColumn columnHan_Tra;
            
            private global::System.Data.DataColumn columnNgay_Thuc_Tra;
            
            private global::System.Data.DataColumn columnTrang_Thai_Muon;
            
            private global::System.Data.DataColumn columnTien_Coc;
            
            private global::System.Data.DataColumn columnMa_Sach;
            
            private global::System.Data.DataColumn columnMa_Dau_Sach;
            
            private global::System.Data.DataColumn columnTrang_Thai_Sach_Muon;
            
            private global::System.Data.DataColumn columnTen_Dau_Sach;
            
            private global::System.Data.DataColumn columnNam_XB;
            
            private global::System.Data.DataColumn columnMa_Doc_Gia;
            
            private global::System.Data.DataColumn columnHo_Ten;
            
            private global::System.Data.DataColumn columnTen_Thu_Thu;
            
            private global::System.Data.DataColumn columnTenKieuMuon;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public dtPhieuMuonDataTable() {
                this.TableName = "dtPhieuMuon";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal dtPhieuMuonDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected dtPhieuMuonDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn Ma_Phieu_MuonColumn {
                get {
                    return this.columnMa_Phieu_Muon;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn Ma_TheColumn {
                get {
                    return this.columnMa_The;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn Ma_Thu_ThuColumn {
                get {
                    return this.columnMa_Thu_Thu;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn Ma_Kieu_MuonColumn {
                get {
                    return this.columnMa_Kieu_Muon;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn Ngay_MuonColumn {
                get {
                    return this.columnNgay_Muon;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn Han_TraColumn {
                get {
                    return this.columnHan_Tra;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn Ngay_Thuc_TraColumn {
                get {
                    return this.columnNgay_Thuc_Tra;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn Trang_Thai_MuonColumn {
                get {
                    return this.columnTrang_Thai_Muon;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn Tien_CocColumn {
                get {
                    return this.columnTien_Coc;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn Ma_SachColumn {
                get {
                    return this.columnMa_Sach;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn Ma_Dau_SachColumn {
                get {
                    return this.columnMa_Dau_Sach;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn Trang_Thai_Sach_MuonColumn {
                get {
                    return this.columnTrang_Thai_Sach_Muon;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn Ten_Dau_SachColumn {
                get {
                    return this.columnTen_Dau_Sach;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn Nam_XBColumn {
                get {
                    return this.columnNam_XB;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn Ma_Doc_GiaColumn {
                get {
                    return this.columnMa_Doc_Gia;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn Ho_TenColumn {
                get {
                    return this.columnHo_Ten;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn Ten_Thu_ThuColumn {
                get {
                    return this.columnTen_Thu_Thu;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn TenKieuMuonColumn {
                get {
                    return this.columnTenKieuMuon;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public dtPhieuMuonRow this[int index] {
                get {
                    return ((dtPhieuMuonRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event dtPhieuMuonRowChangeEventHandler dtPhieuMuonRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event dtPhieuMuonRowChangeEventHandler dtPhieuMuonRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event dtPhieuMuonRowChangeEventHandler dtPhieuMuonRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event dtPhieuMuonRowChangeEventHandler dtPhieuMuonRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void AdddtPhieuMuonRow(dtPhieuMuonRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public dtPhieuMuonRow AdddtPhieuMuonRow(
                        string Ma_Phieu_Muon, 
                        string Ma_The, 
                        string Ma_Thu_Thu, 
                        string Ma_Kieu_Muon, 
                        string Ngay_Muon, 
                        string Han_Tra, 
                        string Ngay_Thuc_Tra, 
                        string Trang_Thai_Muon, 
                        string Tien_Coc, 
                        string Ma_Sach, 
                        string Ma_Dau_Sach, 
                        string Trang_Thai_Sach_Muon, 
                        string Ten_Dau_Sach, 
                        string Nam_XB, 
                        string Ma_Doc_Gia, 
                        string Ho_Ten, 
                        string Ten_Thu_Thu, 
                        string TenKieuMuon) {
                dtPhieuMuonRow rowdtPhieuMuonRow = ((dtPhieuMuonRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        Ma_Phieu_Muon,
                        Ma_The,
                        Ma_Thu_Thu,
                        Ma_Kieu_Muon,
                        Ngay_Muon,
                        Han_Tra,
                        Ngay_Thuc_Tra,
                        Trang_Thai_Muon,
                        Tien_Coc,
                        Ma_Sach,
                        Ma_Dau_Sach,
                        Trang_Thai_Sach_Muon,
                        Ten_Dau_Sach,
                        Nam_XB,
                        Ma_Doc_Gia,
                        Ho_Ten,
                        Ten_Thu_Thu,
                        TenKieuMuon};
                rowdtPhieuMuonRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowdtPhieuMuonRow);
                return rowdtPhieuMuonRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                dtPhieuMuonDataTable cln = ((dtPhieuMuonDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new dtPhieuMuonDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal void InitVars() {
                this.columnMa_Phieu_Muon = base.Columns["Ma_Phieu_Muon"];
                this.columnMa_The = base.Columns["Ma_The"];
                this.columnMa_Thu_Thu = base.Columns["Ma_Thu_Thu"];
                this.columnMa_Kieu_Muon = base.Columns["Ma_Kieu_Muon"];
                this.columnNgay_Muon = base.Columns["Ngay_Muon"];
                this.columnHan_Tra = base.Columns["Han_Tra"];
                this.columnNgay_Thuc_Tra = base.Columns["Ngay_Thuc_Tra"];
                this.columnTrang_Thai_Muon = base.Columns["Trang_Thai_Muon"];
                this.columnTien_Coc = base.Columns["Tien_Coc"];
                this.columnMa_Sach = base.Columns["Ma_Sach"];
                this.columnMa_Dau_Sach = base.Columns["Ma_Dau_Sach"];
                this.columnTrang_Thai_Sach_Muon = base.Columns["Trang_Thai_Sach_Muon"];
                this.columnTen_Dau_Sach = base.Columns["Ten_Dau_Sach"];
                this.columnNam_XB = base.Columns["Nam_XB"];
                this.columnMa_Doc_Gia = base.Columns["Ma_Doc_Gia"];
                this.columnHo_Ten = base.Columns["Ho_Ten"];
                this.columnTen_Thu_Thu = base.Columns["Ten_Thu_Thu"];
                this.columnTenKieuMuon = base.Columns["TenKieuMuon"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            private void InitClass() {
                this.columnMa_Phieu_Muon = new global::System.Data.DataColumn("Ma_Phieu_Muon", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMa_Phieu_Muon);
                this.columnMa_The = new global::System.Data.DataColumn("Ma_The", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMa_The);
                this.columnMa_Thu_Thu = new global::System.Data.DataColumn("Ma_Thu_Thu", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMa_Thu_Thu);
                this.columnMa_Kieu_Muon = new global::System.Data.DataColumn("Ma_Kieu_Muon", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMa_Kieu_Muon);
                this.columnNgay_Muon = new global::System.Data.DataColumn("Ngay_Muon", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNgay_Muon);
                this.columnHan_Tra = new global::System.Data.DataColumn("Han_Tra", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnHan_Tra);
                this.columnNgay_Thuc_Tra = new global::System.Data.DataColumn("Ngay_Thuc_Tra", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNgay_Thuc_Tra);
                this.columnTrang_Thai_Muon = new global::System.Data.DataColumn("Trang_Thai_Muon", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTrang_Thai_Muon);
                this.columnTien_Coc = new global::System.Data.DataColumn("Tien_Coc", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTien_Coc);
                this.columnMa_Sach = new global::System.Data.DataColumn("Ma_Sach", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMa_Sach);
                this.columnMa_Dau_Sach = new global::System.Data.DataColumn("Ma_Dau_Sach", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMa_Dau_Sach);
                this.columnTrang_Thai_Sach_Muon = new global::System.Data.DataColumn("Trang_Thai_Sach_Muon", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTrang_Thai_Sach_Muon);
                this.columnTen_Dau_Sach = new global::System.Data.DataColumn("Ten_Dau_Sach", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTen_Dau_Sach);
                this.columnNam_XB = new global::System.Data.DataColumn("Nam_XB", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNam_XB);
                this.columnMa_Doc_Gia = new global::System.Data.DataColumn("Ma_Doc_Gia", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMa_Doc_Gia);
                this.columnHo_Ten = new global::System.Data.DataColumn("Ho_Ten", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnHo_Ten);
                this.columnTen_Thu_Thu = new global::System.Data.DataColumn("Ten_Thu_Thu", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTen_Thu_Thu);
                this.columnTenKieuMuon = new global::System.Data.DataColumn("TenKieuMuon", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTenKieuMuon);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public dtPhieuMuonRow NewdtPhieuMuonRow() {
                return ((dtPhieuMuonRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new dtPhieuMuonRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(dtPhieuMuonRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.dtPhieuMuonRowChanged != null)) {
                    this.dtPhieuMuonRowChanged(this, new dtPhieuMuonRowChangeEvent(((dtPhieuMuonRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.dtPhieuMuonRowChanging != null)) {
                    this.dtPhieuMuonRowChanging(this, new dtPhieuMuonRowChangeEvent(((dtPhieuMuonRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.dtPhieuMuonRowDeleted != null)) {
                    this.dtPhieuMuonRowDeleted(this, new dtPhieuMuonRowChangeEvent(((dtPhieuMuonRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.dtPhieuMuonRowDeleting != null)) {
                    this.dtPhieuMuonRowDeleting(this, new dtPhieuMuonRowChangeEvent(((dtPhieuMuonRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void RemovedtPhieuMuonRow(dtPhieuMuonRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsPhieuMuon ds = new dsPhieuMuon();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "dtPhieuMuonDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class dtPhieuMuonRow : global::System.Data.DataRow {
            
            private dtPhieuMuonDataTable tabledtPhieuMuon;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal dtPhieuMuonRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabledtPhieuMuon = ((dtPhieuMuonDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string Ma_Phieu_Muon {
                get {
                    try {
                        return ((string)(this[this.tabledtPhieuMuon.Ma_Phieu_MuonColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Ma_Phieu_Muon\' in table \'dtPhieuMuon\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtPhieuMuon.Ma_Phieu_MuonColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string Ma_The {
                get {
                    try {
                        return ((string)(this[this.tabledtPhieuMuon.Ma_TheColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Ma_The\' in table \'dtPhieuMuon\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtPhieuMuon.Ma_TheColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string Ma_Thu_Thu {
                get {
                    try {
                        return ((string)(this[this.tabledtPhieuMuon.Ma_Thu_ThuColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Ma_Thu_Thu\' in table \'dtPhieuMuon\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtPhieuMuon.Ma_Thu_ThuColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string Ma_Kieu_Muon {
                get {
                    try {
                        return ((string)(this[this.tabledtPhieuMuon.Ma_Kieu_MuonColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Ma_Kieu_Muon\' in table \'dtPhieuMuon\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtPhieuMuon.Ma_Kieu_MuonColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string Ngay_Muon {
                get {
                    try {
                        return ((string)(this[this.tabledtPhieuMuon.Ngay_MuonColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Ngay_Muon\' in table \'dtPhieuMuon\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtPhieuMuon.Ngay_MuonColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string Han_Tra {
                get {
                    try {
                        return ((string)(this[this.tabledtPhieuMuon.Han_TraColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Han_Tra\' in table \'dtPhieuMuon\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtPhieuMuon.Han_TraColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string Ngay_Thuc_Tra {
                get {
                    try {
                        return ((string)(this[this.tabledtPhieuMuon.Ngay_Thuc_TraColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Ngay_Thuc_Tra\' in table \'dtPhieuMuon\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtPhieuMuon.Ngay_Thuc_TraColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string Trang_Thai_Muon {
                get {
                    try {
                        return ((string)(this[this.tabledtPhieuMuon.Trang_Thai_MuonColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Trang_Thai_Muon\' in table \'dtPhieuMuon\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtPhieuMuon.Trang_Thai_MuonColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string Tien_Coc {
                get {
                    try {
                        return ((string)(this[this.tabledtPhieuMuon.Tien_CocColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Tien_Coc\' in table \'dtPhieuMuon\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtPhieuMuon.Tien_CocColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string Ma_Sach {
                get {
                    try {
                        return ((string)(this[this.tabledtPhieuMuon.Ma_SachColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Ma_Sach\' in table \'dtPhieuMuon\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtPhieuMuon.Ma_SachColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string Ma_Dau_Sach {
                get {
                    try {
                        return ((string)(this[this.tabledtPhieuMuon.Ma_Dau_SachColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Ma_Dau_Sach\' in table \'dtPhieuMuon\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtPhieuMuon.Ma_Dau_SachColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string Trang_Thai_Sach_Muon {
                get {
                    try {
                        return ((string)(this[this.tabledtPhieuMuon.Trang_Thai_Sach_MuonColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Trang_Thai_Sach_Muon\' in table \'dtPhieuMuon\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtPhieuMuon.Trang_Thai_Sach_MuonColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string Ten_Dau_Sach {
                get {
                    try {
                        return ((string)(this[this.tabledtPhieuMuon.Ten_Dau_SachColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Ten_Dau_Sach\' in table \'dtPhieuMuon\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtPhieuMuon.Ten_Dau_SachColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string Nam_XB {
                get {
                    try {
                        return ((string)(this[this.tabledtPhieuMuon.Nam_XBColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Nam_XB\' in table \'dtPhieuMuon\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtPhieuMuon.Nam_XBColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string Ma_Doc_Gia {
                get {
                    try {
                        return ((string)(this[this.tabledtPhieuMuon.Ma_Doc_GiaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Ma_Doc_Gia\' in table \'dtPhieuMuon\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtPhieuMuon.Ma_Doc_GiaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string Ho_Ten {
                get {
                    try {
                        return ((string)(this[this.tabledtPhieuMuon.Ho_TenColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Ho_Ten\' in table \'dtPhieuMuon\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtPhieuMuon.Ho_TenColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string Ten_Thu_Thu {
                get {
                    try {
                        return ((string)(this[this.tabledtPhieuMuon.Ten_Thu_ThuColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Ten_Thu_Thu\' in table \'dtPhieuMuon\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtPhieuMuon.Ten_Thu_ThuColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string TenKieuMuon {
                get {
                    try {
                        return ((string)(this[this.tabledtPhieuMuon.TenKieuMuonColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TenKieuMuon\' in table \'dtPhieuMuon\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtPhieuMuon.TenKieuMuonColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsMa_Phieu_MuonNull() {
                return this.IsNull(this.tabledtPhieuMuon.Ma_Phieu_MuonColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetMa_Phieu_MuonNull() {
                this[this.tabledtPhieuMuon.Ma_Phieu_MuonColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsMa_TheNull() {
                return this.IsNull(this.tabledtPhieuMuon.Ma_TheColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetMa_TheNull() {
                this[this.tabledtPhieuMuon.Ma_TheColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsMa_Thu_ThuNull() {
                return this.IsNull(this.tabledtPhieuMuon.Ma_Thu_ThuColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetMa_Thu_ThuNull() {
                this[this.tabledtPhieuMuon.Ma_Thu_ThuColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsMa_Kieu_MuonNull() {
                return this.IsNull(this.tabledtPhieuMuon.Ma_Kieu_MuonColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetMa_Kieu_MuonNull() {
                this[this.tabledtPhieuMuon.Ma_Kieu_MuonColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsNgay_MuonNull() {
                return this.IsNull(this.tabledtPhieuMuon.Ngay_MuonColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetNgay_MuonNull() {
                this[this.tabledtPhieuMuon.Ngay_MuonColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsHan_TraNull() {
                return this.IsNull(this.tabledtPhieuMuon.Han_TraColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetHan_TraNull() {
                this[this.tabledtPhieuMuon.Han_TraColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsNgay_Thuc_TraNull() {
                return this.IsNull(this.tabledtPhieuMuon.Ngay_Thuc_TraColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetNgay_Thuc_TraNull() {
                this[this.tabledtPhieuMuon.Ngay_Thuc_TraColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsTrang_Thai_MuonNull() {
                return this.IsNull(this.tabledtPhieuMuon.Trang_Thai_MuonColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetTrang_Thai_MuonNull() {
                this[this.tabledtPhieuMuon.Trang_Thai_MuonColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsTien_CocNull() {
                return this.IsNull(this.tabledtPhieuMuon.Tien_CocColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetTien_CocNull() {
                this[this.tabledtPhieuMuon.Tien_CocColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsMa_SachNull() {
                return this.IsNull(this.tabledtPhieuMuon.Ma_SachColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetMa_SachNull() {
                this[this.tabledtPhieuMuon.Ma_SachColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsMa_Dau_SachNull() {
                return this.IsNull(this.tabledtPhieuMuon.Ma_Dau_SachColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetMa_Dau_SachNull() {
                this[this.tabledtPhieuMuon.Ma_Dau_SachColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsTrang_Thai_Sach_MuonNull() {
                return this.IsNull(this.tabledtPhieuMuon.Trang_Thai_Sach_MuonColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetTrang_Thai_Sach_MuonNull() {
                this[this.tabledtPhieuMuon.Trang_Thai_Sach_MuonColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsTen_Dau_SachNull() {
                return this.IsNull(this.tabledtPhieuMuon.Ten_Dau_SachColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetTen_Dau_SachNull() {
                this[this.tabledtPhieuMuon.Ten_Dau_SachColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsNam_XBNull() {
                return this.IsNull(this.tabledtPhieuMuon.Nam_XBColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetNam_XBNull() {
                this[this.tabledtPhieuMuon.Nam_XBColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsMa_Doc_GiaNull() {
                return this.IsNull(this.tabledtPhieuMuon.Ma_Doc_GiaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetMa_Doc_GiaNull() {
                this[this.tabledtPhieuMuon.Ma_Doc_GiaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsHo_TenNull() {
                return this.IsNull(this.tabledtPhieuMuon.Ho_TenColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetHo_TenNull() {
                this[this.tabledtPhieuMuon.Ho_TenColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsTen_Thu_ThuNull() {
                return this.IsNull(this.tabledtPhieuMuon.Ten_Thu_ThuColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetTen_Thu_ThuNull() {
                this[this.tabledtPhieuMuon.Ten_Thu_ThuColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsTenKieuMuonNull() {
                return this.IsNull(this.tabledtPhieuMuon.TenKieuMuonColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetTenKieuMuonNull() {
                this[this.tabledtPhieuMuon.TenKieuMuonColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public class dtPhieuMuonRowChangeEvent : global::System.EventArgs {
            
            private dtPhieuMuonRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public dtPhieuMuonRowChangeEvent(dtPhieuMuonRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public dtPhieuMuonRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591